baseurl: "" # the subpath of your site, e.g. /blog
url: "https://isagrassl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Isabella Graßl

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


title: Dr. Isabella Graßl
tagline: Personal Webpage of Dr. Isabella Graßl
description: Personal Webpage of Dr. Isabella Graßl