#-------------------------------
# General Site Settings
title: Dr. Isabella Graßl
logo: icon.jpg # You can add own logo.
description: Personal Webpage of Dr. Isabella Graßl


#-------------------------------
# Author Settings
author:
  name: Dr. Isabella Graßl
  image: isa.jpg
  say-hello: <strong>Prof. Dr. Isabella Graßl</strong>
  bio: I am currently a Visiting Professor at Technical University of Darmstadt, specialising in Gender in Computer Science. Previously, I worked as a Research Associate at the University of Cambridge and completed my PhD on diversity in programming at the University of Passau with summa cum laude. With academic backgrounds in both computer science and the humanities, my research takes an interdisciplinary approach. I focus on the human and social aspects of software engineering, exploring how diversity—whether in terms of gender, cultural and ethnic background, beliefs, professional experience, or disabilities—affects collaboration in software teams. At its core, my work aims to better understand how people interact in software teams and how effective collaboration can enhance code quality.I am particularly passionate about supporting young talent in computing. I advocate for creative and gender-sensitive approaches to inspire children and young people—regardless of gender or social background—to engage with computer science. 
  
#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/dr-isabella-graßl-266a1720a

#-------------------------------
# Google Analytics
google-analytics: xRuhi2YAAAAJ # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username





#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
