#-------------------------------
# General Site Settings
title: Dr. Isabella Graßl
logo: icon.jpg # You can add own logo.
description: Personal Webpage of Dr. Isabella Graßl


#-------------------------------
# Author Settings
author:
  name: Dr. Isabella Graßl
  image: isa.jpg
  say-hello: <strong>Prof. Dr. Isabella Graßl</strong>
  bio: Bridging Software Engineering, Education, Data Science, Diversity, and Cultural Studies 🤖 | Advocate for Inclusive Tech Education 🦄 | Passionate About Interdisciplinary Research in the Human and Social Factors of Software Engineering 🚀| Mission to Inspire and Empower Young Minds ✨ 
#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/dr-isabella-graßl-266a1720a

#-------------------------------
# Google Analytics
google-analytics: xRuhi2YAAAAJ # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username





#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
